from .precio_promedio import precio_promedio
from .producto_mayor_precio import producto_mayor_precio
from .producto_menor_precio import producto_menor_precio
from .valor_total_inventario import valor_total_inventario